// import { Product } from './types';

// export const MOCK_PRODUCTS: Product[] = [
//   {
//     id: '1',
//     name: 'Intricate 3D Miniature Castle',
//     vendor: '3D Artisan Studio',
//     category: 'Miniatures',
//     price: 89.99,
//     originalPrice: 120.00,
//     image: '/products/castle.jpg',
//     images: ['/products/castle.jpg', '/products/castle.jpg', '/products/castle.jpg'],
//     description: 'A beautifully detailed 3D printed miniature castle with intricate architecture. Perfect for collectors and display enthusiasts.',
//     rating: 4.8,
//     reviews: 156,
//     inStock: true,
//     tags: ['miniature', 'fantasy', 'architecture', 'collectible'],
//     sku: 'CASTLE-001',
//     color: 'Gray',
//     customizable: true,
//   },
//   {
//     id: '2',
//     name: 'Custom Name Desk Organizer',
//     vendor: 'PrintMaster Design',
//     category: 'Functional Items',
//     price: 34.99,
//     image: '/products/organizer.jpg',
//     images: ['/products/organizer.jpg'],
//     description: 'Sleek desk organizer with customizable name engraving. Keep your workspace organized in style.',
//     rating: 4.6,
//     reviews: 89,
//     inStock: true,
//     tags: ['desk', 'organization', 'functional', 'customizable'],
//     sku: 'ORG-002',
//     color: 'Black',
//     customizable: true,
//   },
//   {
//     id: '3',
//     name: 'Dragon Head Wall Mount',
//     vendor: 'Creative Prints Co',
//     category: 'Home Decor',
//     price: 56.99,
//     originalPrice: 75.00,
//     image: '/products/dragon.jpg',
//     images: ['/products/dragon.jpg'],
//     description: 'Eye-catching 3D printed dragon head sculpture perfect for modern home decor. Great conversation starter!',
//     rating: 4.9,
//     reviews: 234,
//     inStock: true,
//     tags: ['dragon', 'wall decor', 'sculpture', 'fantasy'],
//     sku: 'DRAGON-003',
//     color: 'Red',
//     customizable: false,
//   },
//   {
//     id: '4',
//     name: 'Geometric Jewelry Box',
//     vendor: 'Precision 3D Works',
//     category: 'Home Decor',
//     price: 44.99,
//     image: '/products/jewelry-box.jpg',
//     images: ['/products/jewelry-box.jpg'],
//     description: 'Modern geometric jewelry box with smooth finish. Perfect for organizing accessories with style.',
//     rating: 4.5,
//     reviews: 45,
//     inStock: true,
//     tags: ['jewelry', 'storage', 'geometric', 'home'],
//     sku: 'JBOX-004',
//     color: 'White',
//     customizable: true,
//   },
//   {
//     id: '5',
//     name: 'Baby Dragon Figure Set',
//     vendor: 'Digital Crafts Lab',
//     category: 'Toys & Games',
//     price: 28.99,
//     image: '/products/dragon-set.jpg',
//     images: ['/products/dragon-set.jpg'],
//     description: 'Adorable set of 3D printed baby dragon figures. Perfect for fantasy lovers and collectors.',
//     rating: 4.7,
//     reviews: 167,
//     inStock: true,
//     tags: ['dragon', 'toys', 'fantasy', 'collection'],
//     sku: 'DRAGONSET-005',
//     color: 'Green',
//     customizable: false,
//   },
//   {
//     id: '6',
//     name: 'Botanical Plant Pot',
//     vendor: '3D Artisan Studio',
//     category: 'Home Decor',
//     price: 22.99,
//     originalPrice: 32.00,
//     image: '/products/plant-pot.jpg',
//     images: ['/products/plant-pot.jpg'],
//     description: 'Beautiful botanical-inspired plant pot with drainage hole. Eco-friendly and artistic.',
//     rating: 4.4,
//     reviews: 78,
//     inStock: true,
//     tags: ['plant', 'pot', 'botanical', 'eco-friendly'],
//     sku: 'POT-006',
//     color: 'Terracotta',
//     customizable: true,
//   },
//   {
//     id: '7',
//     name: 'Steampunk Desk Clock',
//     vendor: 'PrintMaster Design',
//     category: 'Functional Items',
//     price: 67.99,
//     image: '/products/clock.jpg',
//     images: ['/products/clock.jpg'],
//     description: 'Intricate steampunk-inspired desk clock. A functional art piece for any workspace.',
//     rating: 4.8,
//     reviews: 201,
//     inStock: true,
//     tags: ['clock', 'steampunk', 'desk', 'functional'],
//     sku: 'CLOCK-007',
//     color: 'Bronze',
//     customizable: false,
//   },
//   {
//     id: '8',
//     name: 'Custom Name Keychain',
//     vendor: 'Creative Prints Co',
//     category: 'Functional Items',
//     price: 8.99,
//     image: '/products/keychain.jpg',
//     images: ['/products/keychain.jpg'],
//     description: 'Personalized 3D printed keychain. Great as a gift or for personal use.',
//     rating: 4.6,
//     reviews: 512,
//     inStock: true,
//     tags: ['keychain', 'personalized', 'gift', 'small'],
//     sku: 'KEYCHAIN-008',
//     color: 'Silver',
//     customizable: true,
//   },
//   {
//     id: '9',
//     name: 'Abstract Art Sculpture',
//     vendor: 'Precision 3D Works',
//     category: 'Art & Collectibles',
//     price: 124.99,
//     originalPrice: 180.00,
//     image: '/products/sculpture.jpg',
//     images: ['/products/sculpture.jpg'],
//     description: 'Modern abstract 3D printed sculpture. A statement piece for contemporary art lovers.',
//     rating: 4.9,
//     reviews: 98,
//     inStock: false,
//     tags: ['art', 'sculpture', 'abstract', 'modern'],
//     sku: 'ART-009',
//     color: 'Blue',
//     customizable: false,
//   },
//   {
//     id: '10',
//     name: 'Hexagon Wall Panel Set',
//     vendor: 'Digital Crafts Lab',
//     category: 'Home Decor',
//     price: 79.99,
//     image: '/products/hexagon.jpg',
//     images: ['/products/hexagon.jpg'],
//     description: 'Set of 6 interlocking hexagon wall panels. Create a custom wall art installation.',
//     rating: 4.7,
//     reviews: 143,
//     inStock: true,
//     tags: ['wall', 'panels', 'geometric', 'modern'],
//     sku: 'HEX-010',
//     color: 'Gold',
//     customizable: true,
//   },
//   {
//     id: '11',
//     name: 'Viking Helmet Replica',
//     vendor: '3D Artisan Studio',
//     category: 'Collectibles',
//     price: 55.99,
//     image: '/products/helmet.jpg',
//     images: ['/products/helmet.jpg'],
//     description: 'Detailed 3D printed replica of a Viking helmet. Perfect for history enthusiasts.',
//     rating: 4.8,
//     reviews: 167,
//     inStock: true,
//     tags: ['viking', 'helmet', 'history', 'replica'],
//     sku: 'VIKING-011',
//     color: 'Silver',
//     customizable: false,
//   },
//   {
//     id: '12',
//     name: 'Modular Shelf Brackets',
//     vendor: 'PrintMaster Design',
//     category: 'Functional Items',
//     price: 29.99,
//     image: '/products/brackets.jpg',
//     images: ['/products/brackets.jpg'],
//     description: 'Modern modular shelf brackets in sets of 4. Sturdy and stylish.',
//     rating: 4.5,
//     reviews: 89,
//     inStock: true,
//     tags: ['shelf', 'brackets', 'functional', 'modular'],
//     sku: 'BRACKET-012',
//     color: 'Black',
//     customizable: true,
//   },
// ];

// export const BEST_SELLERS = MOCK_PRODUCTS.filter((p) => p.reviews > 100).slice(0, 4);
// export const FEATURED_PRODUCTS = MOCK_PRODUCTS.slice(0, 6);

// export const HERO_SLIDES = [
//   {
//     id: '1',
//     title: 'Precision 3D Printed Products',
//     subtitle: 'Handcrafted digital designs brought to life',
//     image: '/hero-slide-1.jpg',
//     cta: 'SHOP NOW',
//   },
//   {
//     id: '2',
//     title: 'Custom Made Just For You',
//     subtitle: 'Personalize your perfect 3D print',
//     image: '/hero-slide-2.jpg',
//     cta: 'CUSTOMIZE NOW',
//   },
//   {
//     id: '3',
//     title: 'Stunning Wall Decor & Art',
//     subtitle: 'Transform your space with 3D printed art',
//     image: '/hero-slide-3.jpg',
//     cta: 'EXPLORE',
//   },
// ];
